### ISSUE TITLE
Add page that alerts admin of suspicious activities in the site.

### ISSUE THREAD

**Issue by johnnyr26** [bbcomputerclub/bbcs-site#17]
If student logs ridiculous # of hours or logs 10 events in one day, this alerts the admin.

**Comment by Allen-B1** [comment]
Keywords
e.g. "CIT" "Counsler"

**Comment by Allen-B1** [comment]
TODO: Add "Not Suspicious" button (for admins obviously)

**Comment by Allen-B1** [comment]
See #36 #34
